### ISSUE TITLE
Error with angular:route

### ISSUE THREAD

**Issue by nschurmann** [OminStyle/yo-angular-ionic-cli#1]
I'm trying to generate a route. But delivers this error:

```
/usr/local/lib/node_modules/generator-angular/route/index.js:20
    bower.devDependencies['angular-route'] ||
                         ^
TypeError: Cannot read property 'angular-route' of undefined
    at new Generator (/usr/local/lib/node_modules/generator-angular/route/index.js:20:26)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:281:10)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:258:15)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:317:24)
    at /usr/local/lib/node_modules/yo/lib/cli.js:91:9
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:50:12)
    at init (/usr/local/lib/node_modules/yo/lib/cli.js:66:7)
    at pre (/usr/local/lib/node_modules/yo/lib/cli.js:53:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:155:1)
    at Module._compile (module.js:456:26)
```

I think that this is because is trying to use angular-route and is defined angular-ui-route as the default.
Any idea on how to change this?

**Comment by charleshan** [comment]
Since yo angular uses angular-route and ionic uses angular-ui-route, generating a route will not work. You could modify the generator to use angular-ui-route instead but I would not recommend doing so because the goal is to try to follow best practice, which I think can be best achieved by using the most popular angular generator. My current solution is just writing the routes manually, which isn't much work at all. I do hope [AngularJS generator](https://github.com/yeoman/generator-angular/) adds support for angular-ui-route.
